name: Build OpenWrt

on:
  release:
    types: published

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_BRANCH: openwrt-19.07
  REPO_TAG: v19.07.3
  CONFIG_FILE: x86-64.config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt && git checkout $REPO_TAG
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc)
        echo "::set-output name=status::success"
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: openwrt_bin
        path: openwrt/bin
